// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLpbLx5QknFHrQ49y-jyYA0pN7hWhOViA',
    appId: '1:427905189558:web:cef24f18c9a01e551dc817',
    messagingSenderId: '427905189558',
    projectId: 'math-game-es3',
    authDomain: 'math-game-es3.firebaseapp.com',
    storageBucket: 'math-game-es3.appspot.com',
    measurementId: 'G-W90YC8MD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaxZ10yp__RCv6ZqiG06Oi-qU6NrBoKVo',
    appId: '1:427905189558:android:0ccf9cfa8788a9a51dc817',
    messagingSenderId: '427905189558',
    projectId: 'math-game-es3',
    storageBucket: 'math-game-es3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqci2_7FglymHshXb5IfYygCy7sL4A2_E',
    appId: '1:427905189558:ios:da190d84be81e1281dc817',
    messagingSenderId: '427905189558',
    projectId: 'math-game-es3',
    storageBucket: 'math-game-es3.appspot.com',
    iosClientId: '427905189558-gibjigjan6jm75h13d0k6tihcuh4itig.apps.googleusercontent.com',
    iosBundleId: 'es3.mathgame.mathGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqci2_7FglymHshXb5IfYygCy7sL4A2_E',
    appId: '1:427905189558:ios:d3793099af24bbb31dc817',
    messagingSenderId: '427905189558',
    projectId: 'math-game-es3',
    storageBucket: 'math-game-es3.appspot.com',
    iosClientId: '427905189558-ru4ffqfifbr8n8t7thl0p94pdkoqnm4u.apps.googleusercontent.com',
    iosBundleId: 'es3.mathgame.mathGame.RunnerTests',
  );
}
